#ifndef WASHER_H
#define WASHER_H

#define WASHER_PERIPHERAL_COUNT (7U)

typedef enum
{
	WASHER_PERIPHERAL_DOOR         = 0x00,

	WASHER_PERIPHERAL_MAIN_VALVE   = 0x01,
	WASHER_PERIPHERAL_PRE_VALVE    = 0x02,

	WASHER_PERIPHERAL_WATER_HEATER = 0x03,
	WASHER_PERIPHERAL_WATER_PUMP   = 0x04,

	WASHER_PERIPHERAL_SONAR        = 0x05;
	WASHER_PERIPHERAL_TAHO         = 0x06;
}
WASHER_PERIPHERAL_t;

typedef struct
{
	uint32_t peripherals[WASHER_PERIPHERAL_COUNT];
}
WASHER_t;

#endif